### ISSUE TITLE
Make DataTables a major release of DataFrames

### ISSUE THREAD

**Issue by rofinn** [JuliaData/DataTables.jl#51]
I'm currently trying to write code that works with both DataFrames and DataTables, but I'm constantly running into name collision issues. It would make my work a lot easier if the DataTables code was simply a major release version of DataFrames.

**Comment by ararslan** [comment]
Initially, what is now DataTables was actually the master branch of DataFrames and the plan was to release it as a version of DataFrames. However, after much deliberation, we decided to separate it into its own repository instead. You can get a bit more history [here](https://discourse.julialang.org/t/datatables-or-dataframes/3160/3). In short, the separation is intentional and we are not going to release the DataTables code as DataFrames.

**Comment by ararslan** [comment]
Eventually there will be an abstraction over tabular data types to which both DataFrames and DataTables will adhere, which will make writing code that works with both much easier. My recommendation is to stick to DataFrames for the time being, at least until the ecosystem around DataTables matures a bit and the future becomes clearer.

**Comment by rofinn** [comment]
Alright, thank you for the prompt response. I didn't realize that switching DataFrames to Nullables would cause so many problem, but this does make sense now.
